### ISSUE TITLE
[FEAT] keyboard event

### ISSUE THREAD

**Issue by forbid403** [forbid403/vue-rangeslider#58]
### features
- [x] choose handle
- [x] move handle
  - [x] left: decrease
  - [x] right: increase
- [x] select value
- [x] fetch value
- [x] backspace event

### TODO
- [x] Modulize functions
- [x] check flowed value with keyboard event
- [x] Add animation when moving keyboard
- [x] Alert values when click enters
- [x] Modulize keyboard selecting functions

**Comment by forbid403** [comment]
<img width="375" alt="K_scenario" src="https://user-images.githubusercontent.com/41617388/90113960-04dde680-dd8d-11ea-9cbb-0d8f572ce291.png">
